export const PRODUCT_LIST_REQ='PRODUCT_LIST_REQ';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQ='PRODUCT_DETAILS_REQ';
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL='PRODUCT_DETAILS_FAIL';

export const CARD_ADD_ITEM ='CARD_ADD_ITEM';

export const CART_REMOVE_ITEM="CART_REMOVE_ITEM";

export const USER_SIGN_REQUEST= 'USER_SIGN_REQUEST';
export const USER_SIGN_SUCCESS= 'USER_SIGN_SUCCESS';
export const USER_SIGN_FAIL= 'USER_SIGN_FAIL';

export const USER_REGISTER_REQUEST= 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS= 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL= 'USER_REGISTER_FAIL';

export const CART_SAVE_SHIPPIN = 'CART_SAVE_SHIPPIN';
export const CART_SAVE_PAYMENT='CART_SAVE_PAYMENT'

export const ORDER_CREATE_REQUEST='ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS='ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL='ORDER_CREATE_FAIL';


//google sign
export const USER_SIGNREQGOOGLE_REQUEST = 'USER_SIGNREQGOOGLE_REQUEST'
export const USER_SIGNREQGOOGLE_SUCESS = 'USER_SIGNREQGOOGLE_SUCCESS'
export const USER_SIGNREQGOOGLE_FAIL = 'USER_SIGNREQGOOGLE_FAIL'


export const PRODUCT_SAVE_REQUEST= 'PRODUCT_SAVE_REQUEST'
export const PRODUCT_SAVE_SUCCESS= 'PRODUCT_SAVE_SUCCESS'
export const PRODUCT_SAVE_FAIL= 'PRODUCT_SAVE_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'


export const USER_UPDATE_REQEST='USER_UPDATE_REQEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'


export const  MY_ORDER_LIST_REQUEST=' MY_ORDER_LIST_REQUEST'
export const  MY_ORDER_LIST_SUCCESS=' MY_ORDER_LIST_SUCCESS'
export const MY_ORDER_LIST_FAIL='MY_ORDER_LIST_FAIL'

export const PRODUCT_DELETE_REQUEST='PRODUCT_DELETE_REQUEST'
export const  PRODUCT_DELETE_SUCCESS =' PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL ='PRODUCT_DELETE_FAIL'

export const ORDER_DETAILS_REQUEST='ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS='ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST='ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'

